---
- hosts: all
  become: yes
  become_user: root
  gather_facts: False
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False
    - setup: # aka resume gathering facts
  roles:
    - { role: common, tags: ["common"] }

- hosts: "aws_tag_Name=app1"
  become: yes
  become_user: root

  roles:
    - { role: word-game, tags: ["word-game"] }

  tasks:
    - name: "get public ip"
      ipify_facts: 
        api_url: "http://api.ipify.org"

    - name: "print public ip"
      debug: msg="{{ ipify_public_ip }}"
